from __future__ import annotations

from datetime import date
from decimal import Decimal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, model_validator

from src.modules.expenses.models import ExpenseStatus
from src.modules.orders.models import PaymentMethod

MAX_AMOUNT = Decimal("99999999.99")


class ExpenseCategoryCreate(BaseModel):
    name: str = Field(min_length=1, max_length=80)
    sort_order: int = 0


class ExpenseCategoryUpdate(BaseModel):
    name: str | None = Field(default=None, min_length=1, max_length=80)
    is_active: bool | None = None
    sort_order: int | None = None


class ExpenseCategoryRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: UUID
    name: str
    is_active: bool
    sort_order: int
    version: int


class ExpenseCreate(BaseModel):
    """An expense as the counter writes it.

    The links are optional and independent, except that a working day cannot be
    named without the person who worked it — a payment for nobody in particular
    is exactly the row that turns up unexplained at the end of the month.
    """

    #: Generated by the device when captured offline (Plan 0004).
    id: UUID | None = None
    expense_date: date | None = None
    category_id: UUID
    concept: str = Field(min_length=1, max_length=160)
    amount: Decimal = Field(gt=0, le=MAX_AMOUNT, decimal_places=2)
    method: PaymentMethod = PaymentMethod.CASH
    status: ExpenseStatus = ExpenseStatus.PAID
    employee_id: UUID | None = None
    #: The working day being paid for. Its overtime amount comes from
    #: `GET /staff/attendance` — the server suggests, a person confirms (D8).
    attendance_record_id: UUID | None = None
    product_lot_id: UUID | None = None
    observations: str | None = Field(default=None, max_length=2000)

    @model_validator(mode="after")
    def _check_links(self) -> ExpenseCreate:
        if self.attendance_record_id is not None and self.employee_id is None:
            raise ValueError("A working day is paid to someone: send the employee too.")
        return self


class ExpenseUpdate(BaseModel):
    """Correcting what was written down. The links are not editable.

    Moving an expense from one working day to another, or onto a different lot,
    is not a correction — it is a different payment, and voiding and re-entering
    it leaves the trace that says so.
    """

    expense_date: date | None = None
    category_id: UUID | None = None
    concept: str | None = Field(default=None, min_length=1, max_length=160)
    amount: Decimal | None = Field(default=None, gt=0, le=MAX_AMOUNT, decimal_places=2)
    method: PaymentMethod | None = None
    status: ExpenseStatus | None = None
    observations: str | None = Field(default=None, max_length=2000)


class ExpenseVoid(BaseModel):
    reason: str = Field(min_length=3, max_length=500)


class ExpenseRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: UUID
    expense_date: date
    category_id: UUID
    #: Carried so the day's list can group by category without a second call.
    category_name: str
    concept: str
    amount: Decimal
    method: PaymentMethod
    status: ExpenseStatus
    employee_id: UUID | None
    employee_name: str | None
    attendance_record_id: UUID | None
    product_lot_id: UUID | None
    observations: str | None
    created_by_id: UUID
    version: int


class ExpensesDaySummary(BaseModel):
    """The day's expenses added up — the right-hand total of the sheet (§6.1)."""

    expense_date: date
    total: Decimal
    #: What has actually left the drawer. The rest is `pending`: owed today,
    #: settled later, and the paper counts it all the same.
    paid_total: Decimal
    pending_total: Decimal
    cash_total: Decimal
    transfer_total: Decimal
    count: int
    by_category: dict[str, Decimal]
